# Generated by Django 4.2.1 on 2023-05-28 10:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('title', models.TextField(db_column='Title', default=None, null=True)),
                ('slug', models.SlugField(db_column='TitleSlug', default=None, null=True)),
                ('sub_title', models.TextField(db_column='SubTitle', default=None, null=True)),
                ('price_from', models.FloatField(db_column='PriceFrom', default=0, null=True)),
                ('price_to', models.FloatField(db_column='PriceTo', default=0, null=True)),
                ('image', models.TextField(db_column='Image', default=None, null=True)),
                ('detail_url', models.TextField(db_column='DirectURL', default=None, null=True)),
                ('source', models.TextField(db_column='Source', default=None, null=True)),
                ('currency_symbol', models.CharField(db_column='CurrencySymbol', default=None, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'db_table': 'ComicsData',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_gin_idx')],
            },
        ),
    ]
