# Generated by Django 4.2.1 on 2023-05-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comicsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicsdata',
            name='slug',
            field=models.TextField(db_column='TitleSlug', default=None, null=True),
        ),
    ]
