# Generated by Django 4.2.1 on 2023-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_comicsdata_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicsdata',
            name='currency_symbol',
            field=models.CharField(db_column='CurrencySymbol', default=None, max_length=255, null=True),
        ),
    ]
