# Generated by Django 4.2.1 on 2023-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_comicsdata_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicsdata',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
    ]
