# Generated by Django 4.2.1 on 2023-06-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comicsdata_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComicsData',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fcm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(db_column='AccessToken', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_column='IsEmailVerified', default=True),
        ),
        migrations.DeleteModel(
            name='EmailVerificationLink',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
