# Generated by Django 4.2.1 on 2023-06-05 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_comicsdata_remove_user_fcm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('title', models.CharField(db_column='Title', default=None, max_length=255, null=True)),
                ('description', models.TextField(db_column='Description', default=None, null=True)),
                ('start_date_time', models.DateTimeField(db_column='StartDateTime', default=None, null=True)),
                ('end_date_time', models.DateTimeField(db_column='EndDateTime', default=None, null=True)),
                ('coordinates', models.TextField(db_column='Coordinates', default=None, null=True)),
                ('images_urls', models.TextField(db_column='ImagesUrls', default=None, null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='user_travel_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TravelData',
            },
        ),
    ]
