# Generated by Django 4.2.1 on 2023-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_traveldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldata',
            name='color',
            field=models.CharField(db_column='Color', default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_id',
            field=models.TextField(db_column='token_id', default=None, null=True),
        ),
    ]
