# Generated by Django 4.2.1 on 2023-06-16 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_traveldata_color_user_token_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldata',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='traveldata',
            name='images_urls',
        ),
        migrations.CreateModel(
            name='TravelSegmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('segment_description', models.TextField(db_column='Description', default=None, null=True)),
                ('segment_start_date_time', models.DateTimeField(db_column='StartDateTime', default=None, null=True)),
                ('segment_end_date_time', models.DateTimeField(db_column='EndDateTime', default=None, null=True)),
                ('coordinates', models.TextField(db_column='Coordinates', default=None, null=True)),
                ('images_urls', models.TextField(db_column='ImagesUrls', default=None, null=True)),
                ('travel', models.ForeignKey(db_column='TravelID', on_delete=django.db.models.deletion.CASCADE, related_name='travel_data_segment', to='users.traveldata')),
            ],
            options={
                'db_table': 'TravelSegmentData',
            },
        ),
    ]
