# Generated by Django 4.2.1 on 2023-06-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_travelsegmentdata_images_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(db_column='StartDateTime', default=None, null=True)),
                ('end_date_time', models.DateTimeField(db_column='EndDateTime', default=None, null=True)),
                ('latitude', models.TextField(db_column='latitude', default=None, null=True)),
                ('lng', models.TextField(db_column='longitude', default=None, null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='user_travel_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TravelHistoryData',
            },
        ),
    ]
